[[project]]
title = "INTILAB Researcher Slider"
category = "Web Development"
image = "https://imgur.com/2nNXhDN.png"
url = "https://github.com/ErasmoMontufar/intilab_researcher_slider"

[[project]]
title = "Smart Vision Virtual Assistant"
category = "Artificial Intelligence"
image = "https://imgur.com/kyHrBGk.png"
url = "https://github.com/ErasmoMontufar/virtual_assistant_ai"

[[project]]
title = "CRUD System with Flask and MongoDB"
category = "Cybersecurity"
image = "https://imgur.com/7110Lj1.png"
url = "https://github.com/ErasmoMontufar/crud_flask_mongodb"

[[project]]
title = "Finance Web Application"
category = "RESTful APIs"
image = "./config/assets/projects/project-1.jpg"
url = "https://github.com/ErasmoMontufar/finance_web_app"

[[project]]
title = "Task Management System"
category = "Applications"
image = "./config/assets/projects/project-8.jpg"
url = "https://github.com/ErasmoMontufar/task_manager_app"

